#!/usr/bin/env sh

function hostips {
    host "$1.corp.smarkets.com" | cut -d' ' -f4
}

function _sshsm {
    if [ "$#" -eq 3 ]; then
        ssh $2 "$1@$3.corp.smarkets.com"
    else
        ssh "$1@$2.corp.smarkets.com"
    fi
}

export ANSIBLE_VAULT_PASSWORD_FILE="$HOME/ansible/.ansible_vault_key"
#source $HOME/ansible/.ansible_secret_environment

alias smarkets="cd $HOME/work/smarkets"
alias dev="source $HOME/work/smarkets/tools/dev/setup/activate.sh"

alias ansible_env="cd $HOME/work/smarkets/tools/ansible"
alias cloud_env="cd $HOME/work/smarkets/tools/cloud"

alias hostips=hostips
alias sshsm="_sshsm jaime"
alias sshsma="_sshsm admin.jaime"
